apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
  - merge:
      mergeKeys:
      - values.cluster
      generators:
      - git:
          repoURL: git@github.com:pradithya/argocd-hack.git
          revision: main
          directories:
          - path: clusters/*/*/infrastructure/istio
          values:
            environment: '{{ index .path.segments 1 }}'
            cluster: '{{ index .path.segments 2 }}'
            chartVersion: 1.22.0
      - clusters:
          selector:
            matchLabels:
              environment: staging
          values:
            cluster: '{{ .name }}'
            chartVersion: 1.23.0
  template:
    metadata:
      name: istio-{{ .values.cluster }}
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      destination:
        name: '{{ .values.cluster }}'
        namespace: infrastructure
      sources:
      - repoURL: git@github.com:pradithya/argocd-hack.git
        targetRevision: main
        ref: values
      - repoURL: https://istio-release.storage.googleapis.com/charts
        chart: base
        targetRevision: '{{ .values.chartVersion }}'
        helm:
          releaseName: istio-base
          valueFiles:
          - $values/components/istio/istio-base.yaml
          - $values/clusters/{{ .values.environment }}/override/istio/istio-base.yaml
          - $values/clusters/{{ .values.environment }}/{{ .values.cluster }}/infrastructure/istio/istio-base.yaml
          ignoreMissingValueFiles: true
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true


