apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomized-helm
spec:
  project: default
  destination:
    name: in-cluster
    namespace: argocd
  source:
    repoURL: git@github.com:pradithya/argocd-hack.git
    targetRevision: main
    path: examples/kustomize-helm-app
  syncPolicy:
    automated: {}
