apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomized-helm-plugin
spec:
  project: default
  destination:
    name: in-cluster
    namespace: argocd
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: master
    path: examples/kustomize-helm-plugin-app
    plugin:
      name: kustomize-helm
      parameters:
      - name: repoURL
        string: https://kubernetes.github.io/ingress-nginx
      - name: chart 
        string: ingress-nginx
      - name: version 	
        string: "4.11.2"
      - name: releaseName
        string: test
      - name: valueFiles
        array: ["kustomize-helm-plugin-app/values.yaml"]
      - name: kustomizationTemplate
        string: |
          apiVersion: kustomize.config.k8s.io/v1beta1
          kind: Kustomization
          resources:
          - deployment.yaml
          - service.yaml
          - kustomization.yaml
          patchesStrategicMerge:
          - patch.yaml
  syncPolicy:
    automated: {}